install:
  - gem install minitest
  - gem install minitest-stub-const

language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - jruby-19mode # JRuby in 1.9 mode
  - jruby-head
before_install: gem install bundler -v 1.10.2
